services:
  apache:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini

  db:
    # Use root/example as user/password credentials
    image: mysql:5.6
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./my.conf:/etc/mysql/conf.d/my.conf

  # to view db if necessary
  adminer:
    image: adminer
    ports:
      - 8080:8080
